name = "helpmycv-backend"
compatibility_date = "2025-02-04"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "helpmycv"
database_id = "local-helpmycv"

[[r2_buckets]]
binding = "R2"
bucket_name = "helpmycv"

[[env.production.d1_databases]]
binding = "DB"
database_name = "helpmycv"
database_id = "531e5932-7518-4e2c-83bf-2aa86822be85"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "helpmycv"
